const appData = {
    navigators: [
        {
            name: "Socrates",
            lifespan: "469-399 BCE",
            title: "A PRF Analysis of Philosophical Inquiry and Examined Life",
            summary: "This analysis necessarily relies on reconstructive interpretation of Socrates through the accounts of Plato, Xenophon, and Aristophanes, as Socrates wrote no philosophical works himself.",
            bioLink: "https://www.britannica.com/biography/Socrates",
            videoUrl: null,
            assemblyHistory: `<p><strong>Early Formation (469-450 BCE):</strong> Socrates's Personal Reality Framework emerged during the height of Athenian democracy and cultural achievement, where traditional religious and social authorities were being questioned while new forms of intellectual inquiry and political participation were developing.</p><p><strong>Philosophical Awakening and Method Development (450-430 BCE):</strong> Socrates's transition from conventional citizen to philosophical inquirer involved developing his distinctive approach to systematic questioning and moral investigation.</p><p><strong>Teaching and Public Engagement (430-399 BCE):</strong> Socrates's mature period involved applying his philosophical method to systematic investigation of moral and political questions while attracting devoted followers and dangerous enemies.</p>`,
            broa: `<p><strong>Belief System (B):</strong> Knowledge-Virtue Unity: Genuine knowledge and virtue are identical. "The unexamined life is not worth living."</p><p><strong>Rule System (R):</strong> Systematic Questioning: Subject all important beliefs to rigorous logical examination. Live according to philosophical conclusions regardless of social consequences.</p><p><strong>Ontological Commitments (O):</strong> Soul-Body Dualism: The soul is distinct from and more important than the body. Objective Moral Reality: Moral truths exist independently of human opinion.</p><p><strong>Authenticity Criteria (A+):</strong> Philosophical-Practical Integration: Authentic existence requires alignment between philosophical convictions and practical action.</p>`,
            atcf: "Successfully integrated his artisan background, military service, and traditional religious formation while developing revolutionary approaches to philosophical inquiry and moral education. His trial and death provided the ultimate demonstration of his principles.",
            fop: "Development of systematic approaches to rational inquiry (the Socratic Method) that could serve ongoing philosophical investigation and moral education across different historical circumstances, establishing critical self-reflection as essential for authentic human existence.",
            capabilities: ["Dialogical Method Innovation", "Cross-Class Communication", "Moral-Intellectual Integration", "Teaching Through Questions"],
            relatedChapters: []
        },
        {
            name: "Harriet Tubman",
            lifespan: "c. 1822-1913",
            title: "A PRF Analysis of Liberation, Leadership, and Cross-Scale Coordination",
            summary: "Harriet Tubman's Personal Reality Framework emerged from the intersection of brutal systemic oppression, profound spiritual experiences, and early manifestations of extraordinary coordination capabilities.",
            bioLink: "https://www.britannica.com/biography/Harriet-Tubman",
            videoUrl: null,
            assemblyHistory: `<p><strong>Early Formation (c. 1822-1844):</strong> Emerged from brutal systemic oppression, profound spiritual experiences, and early manifestations of extraordinary coordination capabilities that would later enable unprecedented rescue operations.</p><p><strong>Mature Development (1844-1860):</strong> Her 1849 escape to Philadelphia marked the crystallization of her core identity—integrating personal liberation with universal liberation imperatives. Developed sophisticated rescue operations with a perfect record.</p><p><strong>Late Integration (1860-1913):</strong> Her service as a Civil War spy, scout, and raid leader represented a successful adaptation of liberation coordination capabilities to formal military contexts.</p>`,
            broa: `<p><strong>Belief System (B):</strong> A divine liberation imperative, believing God directly commanded her activities through visions. A core conviction in universal freedom for all.</p><p><strong>Rule System (R):</strong> Never leave anyone behind. Absolute commitment to operational security through coded language and misdirection. Adaptive tactical flexibility based on changing circumstances.</p><p><strong>Ontological Commitments (O):</strong> An interconnected liberation, recognizing that individual freedom is incomplete without collective liberation.</p><p><strong>Authenticity Criteria (A+):</strong> A spiritual-material integration where authentic action required coordination between mystical insight and practical effectiveness.</p>`,
            atcf: "Successfully integrated traumatic childhood experiences, mystical spiritual development, and emerging liberation imperatives while maintaining narrative coherence and purpose throughout major life transitions without fragmenting identity or compromising essential commitments.",
            fop: "The development of systematic emancipation networks and intergenerational freedom transmission, understanding that authentic liberation required creating conditions where future generations could develop and maintain freedom.",
            capabilities: ["Cross-Temporal Information Processing", "Multi-Scale Network Coordination", "Adaptive Leadership Under Stress", "Strategic Deception and Truth-Telling"],
            relatedChapters: []
        },
        {
            name: "Mahatma Gandhi",
            lifespan: "1869-1948",
            title: "A PRF Analysis of Satyagraha, Self-Transformation, and Civilizational Coordination",
            summary: "Mohandas Gandhi's Personal Reality Framework emerged from the intersection of traditional Hindu cultural inheritance, British colonial educational systems, and early encounters with moral complexity.",
            bioLink: "https://www.britannica.com/biography/Mahatma-Gandhi",
            videoUrl: null,
            assemblyHistory: `<p><strong>Early Formation (1869-1893):</strong> Emerged from traditional Hindu cultural inheritance, British colonial educational systems, and early encounters with moral complexity that would drive him toward developing systematic approaches to truth-force (satyagraha).</p><p><strong>South African Development (1893-1915):</strong> Experiences as a barrister confronting systematic racial discrimination catalyzed the development of satyagraha as a systematic method for transforming unjust power relations.</p><p><strong>Indian Independence Leadership (1915-1948):</strong> Leadership of Indian independence movements demonstrated remarkable capacity for coordinating diverse cultural, religious, and political contexts while maintaining coherent strategic objectives.</p>`,
            broa: `<p><strong>Belief System (B):</strong> A profound conviction that truth (satya) possesses inherent transformative power. Believed that authentic social change requires simultaneous personal transformation.</p><p><strong>Rule System (R):</strong> A systematic refusal to separate means from ends, insisting that methods must embody the values they seek to achieve. Graduated resistance, from dialogue to civil disobedience.</p><p><strong>Ontological Commitments (O):</strong> An integrated reality, where individual consciousness, social relationships, and political structures represent different dimensions of a single coherent whole.</p><p><strong>Authenticity Criteria (A+):</strong> Truth-Action Consistency: Authentic behavior required complete integration between inner conviction and outer expression, refusing compromise regardless of convenience.</p>`,
            atcf: "Successfully integrated traditional Hindu spiritual frameworks, British legal training, and innovative political methodology while maintaining narrative coherence and cultural authenticity throughout major personal and historical transformations.",
            fop: "The dissemination of the Satyagraha methodology and a vision for a global civilization transformation toward patterns that could serve universal human development while preserving environmental sustainability.",
            capabilities: ["Multi-Scale Movement Integration", "Cross-Cultural Communication", "Conflict Transformation Innovation", "Organizational Leadership Under Stress"],
            relatedChapters: []
        },
         {
            name: "Dorothy Day",
            lifespan: "1897-1980",
            title: "A PRF Analysis of Radical Hospitality, Personalist Revolution, and Prophetic Witness",
            summary: "Dorothy Day's Personal Reality Framework emerged from the intersection of radical secular journalism, personal experience of poverty and marginalization, and profound encounters with spiritual transformation.",
            bioLink: "https://www.britannica.com/biography/Dorothy-Day",
            videoUrl: null,
            assemblyHistory: `<p><strong>Early Formation (1897-1927):</strong> Emerged from radical secular journalism, personal experience of poverty, and profound encounters with spiritual transformation that would drive her toward developing systematic approaches to personalist revolution.</p><p><strong>Catholic Worker Movement Development (1933-1950):</strong> Her encounter with Peter Maurin (1932) catalyzed the synthesis of her journalistic capabilities, radical political analysis, and Catholic spiritual commitment into the Catholic Worker Movement.</p><p><strong>Prophetic Witness and Pacifist Leadership (1940-1980):</strong> Her absolute commitment to nonviolence during World War II, including opposition to 'the good war,' demonstrated exceptional capacity for maintaining principle-based positions despite massive social pressure.</p>`,
            broa: `<p><strong>Belief System (B):</strong> A profound conviction that all human beings participate in the Mystical Body of Christ, making service to the poor a direct encounter with the divine. A core belief that authentic social transformation requires simultaneous personal conversion and structural change.</p><p><strong>Rule System (R):</strong> An absolute commitment to direct service through the works of mercy as the primary form of political action. A consistent application of nonviolent methods in all conflicts.</p><p><strong>Ontological Commitments (O):</strong> An Incarnational Reality, where material conditions and spiritual realities interpenetrate rather than existing in separate spheres.</p><p><strong>Authenticity Criteria (A+):</strong> A spiritual-political integration, where authentic action required coordination between contemplative spiritual practice and radical political engagement.</p>`,
            atcf: "Successfully integrated her bohemian radical background, personal crisis and conversion, and evolving Catholic Worker leadership while maintaining narrative coherence and an authentic voice throughout major personal and social transformations.",
            fop: "The development of sustainable frameworks for Catholic Worker communities that could continue radical Christian witness across generations, and the establishment of models for coordinating contemplative spiritual practice with radical political action.",
            capabilities: ["Cross-Class Communication", "Religious-Secular Bridge Building", "Organizational Leadership Through Service", "Movement Coordination Under Opposition"],
            relatedChapters: []
        },
        {
            name: "Oskar Schindler",
            lifespan: "1908-1974",
            title: "A PRF Analysis of Moral Transformation, Strategic Compassion, and System Subversion",
            summary: "Oskar Schindler's Personal Reality Framework initially developed within contexts of conventional business ambition, cultural assimilation, and opportunistic adaptation.",
            bioLink: "https://encyclopedia.ushmm.org/content/en/article/oskar-schindler",
            videoUrl: null,
            assemblyHistory: `<p><strong>Early Formation (1908-1939):</strong> Initially developed within contexts of conventional business ambition and opportunistic adaptation that would later provide crucial capabilities for life-saving operations.</p><p><strong>Industrial Operations and Moral Awakening (1939-1943):</strong> His increasing employment of Jewish workers evolved from economic calculation (cheap labor) through protective concern to a systematic life-saving operation.</p><p><strong>Systematic Rescue Operations (1943-1945):</strong> His establishment of armaments production and compilation of 'Schindler's List' represented a sophisticated integration of bureaucratic manipulation, economic leverage, and personal relationship management.</p>`,
            broa: `<p><strong>Belief System (B):</strong> A progressive development of the conviction that individual human lives possessed absolute worth that transcended economic or political categories. A core belief that unjust systems could and should be undermined through strategic deception.</p><p><strong>Rule System (R):</strong> Absolute commitment to maintaining the safety and welfare of his Jewish employees through whatever means necessary. Systematic use of charm, bribery, and false documentation to create protective spaces.</p><p><strong>Ontological Commitments (O):</strong> A belief in moral agency under constraints, understanding that human beings are capable of authentic moral choice even within systematically evil contexts.</p><p><strong>Authenticity Criteria (A+):</strong> A moral-strategic integration where authentic action required coordination between genuine humanitarian concern and effective tactical implementation.</p>`,
            atcf: "Successfully integrated his opportunistic business background, Nazi Party membership, and evolving humanitarian commitments while maintaining a narrative coherence that preserved his authentic moral development throughout major personal and historical transformations.",
            fop: "The development of frameworks for ensuring rescued workers' transition to post-war life, and the understanding that successful resistance to systematic evil required a sophisticated integration of strategic deception with authentic moral commitment.",
            capabilities: ["Cross-Cultural Manipulation", "Economic-Humanitarian Integration", "Authority Deception and Worker Protection", "Network Coordination Under Surveillance"],
            relatedChapters: []
        },
        {
            name: "Martin Luther King Jr.",
            lifespan: "1929-1968",
            title: "A PRF Analysis of Beloved Community, Nonviolent Revolution, and Prophetic Democracy",
            summary: "Martin Luther King Jr.'s Personal Reality Framework emerged from the intersection of Black Baptist intellectual tradition, elite educational opportunities, and early encounters with systematic racial oppression.",
            bioLink: "https://www.britannica.com/biography/Martin-Luther-King-Jr",
            videoUrl: null,
            assemblyHistory: `<p><strong>Early Formation (1929-1948):</strong> Emerged from the intersection of the Black Baptist intellectual tradition, elite educational opportunities, and early encounters with systematic racial oppression.</p><p><strong>Montgomery Leadership Development (1955-1960):</strong> His leadership of the bus boycott demonstrated a remarkable capacity for coordinating diverse community constituencies while maintaining strategic nonviolent discipline.</p><p><strong>National Movement Leadership (1960-1968):</strong> His leadership of the SCLC demonstrated sophisticated capacity for coordinating multiple local movements while maintaining coherent strategic objectives across diverse contexts.</p>`,
            broa: `<p><strong>Belief System (B):</strong> A profound conviction that all human beings bear God's image, making racial segregation both spiritually blasphemous and politically illegitimate. A core belief that authentic Christian love (agape) can transform social relationships and create a 'Beloved Community'.</p><p><strong>Rule System (R):</strong> An unwavering commitment to nonviolent methods in all circumstances. A systematic focus on converting opponents rather than defeating them.</p><p><strong>Ontological Commitments (O):</strong> An understanding of reality as fundamentally structured toward justice, where the 'arc of the moral universe is long, but it bends toward justice'.</p><p><strong>Authenticity Criteria (A+):</strong> A spiritual-political synthesis where authentic leadership required coordination between genuine Christian commitment and effective political action.</p>`,
            atcf: "Successfully integrated the Black Baptist intellectual tradition, academic theological training, and emerging civil rights leadership while maintaining narrative coherence and an authentic spiritual voice throughout major personal and social transformations.",
            fop: "The development of systematic frameworks for creating inclusive democratic communities (the Beloved Community) that could serve as models for ongoing social transformation beyond immediate civil rights victories.",
            capabilities: ["Multi-Constituency Communication", "Strategic-Spiritual Integration", "Mass Movement Leadership", "Prophetic Authority Exercise"],
            relatedChapters: []
        },
        // --- Original figures below this line ---
        {
            name: "Sophie Scholl",
            lifespan: "1921-1943",
            title: "The Conscientious Resister",
            summary: "A member of the White Rose non-violent resistance group in Nazi Germany, executed for distributing anti-war leaflets.",
            bioLink: "https://www.britannica.com/biography/Sophie-Scholl",
            videoUrl: null,
            identityKernel: "A principled conscience and profound moral courage. Raised in a Christian family opposed to Nazism, she believed ordinary citizens had a duty to speak out against evil and protect human dignity.",
            prf: "Her reality was the oppressive Nazi regime during WWII. After an initial period in the Hitler Youth, she experienced a profound dissonance between Nazi propaganda and her Christian ethics, which awakened her resistance.",
            futurePull_RMB: "She acted with the hope of a future Germany free from tyranny. The White Rose leaflets were not just a protest but an attempt to awaken the conscience of other Germans to build a different, more humane future.",
            atcf: "Though her life was short, her narrative is a dramatic arc of ethical awakening and steadfastness. She transformed from a compliant youth into an anti-Nazi martyr, fulfilling her core values of truth and justice even at the cost of her life.",
            dramaticExample: "Her calm defiance during her trial for treason. When caught distributing leaflets, she refused to recant her beliefs, telling the judge, 'Somebody, after all, had to make a start.' She was executed by guillotine just hours later.",
            capabilities: ["Capability for Youth Activism and Dissent", "Capability for Articulating Moral Conscience", "Capability for Ultimate Sacrifice for Principle"],
            relatedChapters: [{ chapter: "4", topic: "Reasoning in an Ethical World" }, { chapter: "5", topic: "Agents in Ethical Systems" }, { chapter: "13", topic: "Protest, Dissent, and Disruption" }]
        },
        {
            name: "Malcolm X",
            lifespan: "1925–1965",
            title: "The Evolving Revolutionary",
            summary: "An influential African American leader who advocated for Black empowerment, evolving from separatism to a more inclusive human rights vision.",
            bioLink: "https://www.britannica.com/biography/Malcolm-X",
            videoUrl: null,
            identityKernel: "Marked by an evolution from advocating Black nationalism and self-defense 'by any means necessary' to a more inclusive vision of human rights, with integrity and courage as constants throughout.",
            prf: "Shaped by personal trauma (his father's murder) and systemic racism. The Nation of Islam provided an initial framework, which he later outgrew after his pilgrimage to Mecca exposed him to a different reality of racial unity.",
            futurePull_RMB: "Initially pulled by a future of Black self-sufficiency and separation. Later, after his Hajj, he was pulled by a new vision of racial brotherhood and global human rights, which he worked to build in his final year.",
            atcf: "A narrative of profound transformation, coherently explained by his own public acknowledgment of his growth. He maintained a consistent drive for justice and truth, even as his specific beliefs evolved dramatically.",
            dramaticExample: "His pilgrimage to Mecca in 1964, which radically changed his views on race and Islam. He returned to the US and publicly renounced the Nation of Islam's separatist doctrines, an act of intellectual honesty that put his life at great risk.",
            capabilities: ["Capability for Self-Transformation and Public Revision", "Capability for Articulating Oppressed Voices", "Capability for Intellectual Honesty"],
            relatedChapters: [{ chapter: "3", topic: "Ethical Perception in a Filtered World" }, { chapter: "6", topic: "Identity, Trauma, and Ethical Disruption" }, { chapter: "13", topic: "Citizenship, Identity, and Belonging" }]
        },
        {
            name: "Nelson Mandela",
            lifespan: "1918–2013",
            title: "The Architect of Reconciliation",
            summary: "A South African anti-apartheid revolutionary who became the country's first Black president, leading a transition to a multiracial democracy.",
            bioLink: "https://www.britannica.com/biography/Nelson-Mandela",
            videoUrl: null,
            identityKernel: "An unshakeable commitment to justice, equality, and reconciliation. Famously stated at his trial that a democratic and free society was an ideal 'for which I am prepared to die.'",
            prf: "Fought against the oppressive system of apartheid. His context shifted from nonviolent protest to armed resistance (targeting infrastructure) after the Sharpeville Massacre, and then to 27 years of imprisonment.",
            futurePull_RMB: "Guided by the vision of a future 'Rainbow Nation.' He studied the language and culture of his oppressors while in prison to prepare for future negotiations and reconciliation, acting in the present for the future he envisioned.",
            atcf: "A consistent narrative from activist to prisoner to president. He emerged from prison not with bitterness, but with a focus on forgiveness, establishing the Truth and Reconciliation Commission instead of seeking retribution.",
            dramaticExample: "Donning the Springbok rugby jersey—a symbol of white Afrikaner pride—at the 1995 Rugby World Cup final. This single gesture became a powerful symbol of his commitment to national unity and reconciliation over vengeance.",
            capabilities: ["Capability for Forgiveness and Reconciliation", "Capability for Long-Term Strategic Patience", "Capability for Holding Contradictory Roles (Freedom Fighter and Peacemaker)"],
            relatedChapters: [{ chapter: "7", topic: "Justice and the Architecture of Fairness" }, { chapter: "13", topic: "Building Political Coherence" }, { chapter: "14", topic: "Ethics Across Time and Legacy" }]
        },
        {
            name: "Rachel Carson",
            lifespan: "1907–1964",
            title: "The Ecological Conscience",
            summary: "A marine biologist and author whose book 'Silent Spring' is credited with advancing the global environmental movement.",
            bioLink: "https://www.britannica.com/biography/Rachel-Carson",
            videoUrl: null,
            identityKernel: "A sense of wonder for the natural world and a moral conviction to protect it through scientific truth-telling. An identity as a responsible citizen-scientist who must alert society to danger.",
            prf: "Operated in a post-WWII American culture that celebrated chemical pesticides like DDT as miracles of science. As a woman scientist, she faced gendered attacks from the powerful chemical industry meant to discredit her as 'hysterical.'",
            futurePull_RMB: "Her work was driven by the imagined future of a 'silent spring' where birds and wildlife were decimated by pesticides. This vision of potential catastrophe motivated her urgent action in the present.",
            atcf: "A narrative of awakening to an ethical calling. She evolved from a nature writer to a reluctant but steadfast advocate, consistently acting out of care for living creatures, even while battling the cancer that would take her life.",
            dramaticExample: "Publishing *Silent Spring* in 1962 despite a massive smear campaign from the powerful chemical industry. Her meticulous research and clear, eloquent prose successfully awakened the public and led to major environmental reforms.",
            capabilities: ["Capability for Translating Science into Public Moral Action", "Capability for Resisting Corporate Disinformation", "Capability for Ecological Empathy"],
            relatedChapters: [{ chapter: "8", topic: "Technological Frontiers" }, { chapter: "9", topic: "Environmental Cartography" }, { chapter: "5", topic: "Agents in Ethical Systems" }]
        },
        {
            name: "Jonas Salk",
            lifespan: "1914–1995",
            title: "The Humanitarian Scientist",
            summary: "Developed the first successful polio vaccine and famously refused to patent it, viewing it as a gift to humanity.",
            bioLink: "https://www.britannica.com/biography/Jonas-Salk",
            videoUrl: null,
            identityKernel: "Grounded in humanitarianism and scientific benevolence. His core value was to alleviate human suffering, viewing his work as a public good rather than a source of personal profit.",
            prf: "Worked during terrifying polio epidemics with massive public support from the March of Dimes. This shaped his view that the resulting vaccine was already 'owned' by the people who funded the research.",
            futurePull_RMB: "Guided by a future where polio was eradicated and life-saving science was accessible to all. He acted to maximize the global distribution of the vaccine, ensuring it reached the most people possible.",
            atcf: "A consistent narrative of scientific morality. From his early research to founding the Salk Institute, he demonstrated an ethos of open, human-centered science, always prioritizing public health over personal gain.",
            dramaticExample: "When asked by journalist Edward R. Murrow who owned the patent to the polio vaccine, he famously replied, 'Well, the people, I would say. There is no patent. Could you patent the sun?' This decision forfeited billions in potential personal wealth.",
            capabilities: ["Capability for Scientific Altruism", "Capability for Public Trust Building", "Capability for Redefining the Value of an Invention"],
            relatedChapters: [{ chapter: "8", topic: "Ethical Design and Hidden Values" }, { chapter: "10", topic: "Rethinking Value" }, { chapter: "12", topic: "The Moral Terrain of Health and Healing" }]
        },
        {
            name: "Ai Weiwei",
            lifespan: "b. 1957",
            title: "The Dissident Artist",
            summary: "A Chinese contemporary artist and activist who uses his work to critique authoritarianism and advocate for human rights.",
            bioLink: "https://www.britannica.com/biography/Ai-Weiwei",
            videoUrl: null,
            identityKernel: "An unflinching commitment to freedom of expression, truth, and justice. He sees creativity and dissent as inseparable acts of human dignity and challenges power without fear.",
            prf: "Shaped by his family's persecution under Mao and his exposure to Western ideas. He operates against the backdrop of an authoritarian Chinese state that censors dissent and punishes critics with imprisonment and violence.",
            futurePull_RMB: "Envisions a future China that respects human rights and free expression. This vision fuels his present-day activism and art, regardless of the severe personal cost, as he works to create a more open society.",
            atcf: "A consistent narrative of creative resistance. From his early art to his global advocacy, he has unwaveringly used his platform to speak truth to power, even after being beaten, detained for 81 days, and surveilled.",
            dramaticExample: "After his secret detention in 2011, he created the work 'S.A.C.R.E.D.,' a series of dioramas depicting his imprisonment. This act turned his personal trauma into a public witness against the state's abuses, refusing to be silenced.",
            capabilities: ["Capability for Artistic Dissent", "Capability for Using Technology for Transparency", "Capability for Enduring State Repression"],
            relatedChapters: [{ chapter: "5", topic: "Agents in Ethical Systems" }, { chapter: "13", topic: "Protest, Dissent, and Disruption" }, { chapter: "8", topic: "Technologies That Shape Us" }]
        },
        {
            name: "The 14th Dalai Lama",
            lifespan: "b. 1935",
            title: "The Compassionate Leader",
            summary: "The spiritual leader of Tibetan Buddhism, advocating for nonviolence, compassion, and interfaith harmony while in exile.",
            bioLink: "https://www.dalailama.com/the-dalai-lama/biography-and-daily-life/brief-biography",
            videoUrl: null,
            identityKernel: "A compassionate servant of peace, embodying Buddhist values of nonviolence (ahimsa), humility, and universal responsibility. He consistently refers to himself as 'a simple monk.'",
            prf: "Thrust into the role of head of state of Tibet during the Chinese invasion. He has spent over 60 years in exile, leading his people while navigating a complex international diplomatic arena and constant pressure from Beijing.",
            futurePull_RMB: "Guided by a vision of a peaceful, autonomous Tibet and a more compassionate world. His 'Middle Way' approach seeks a mutually beneficial solution for the future rather than total independence or continued conflict.",
            atcf: "A narrative of steadfast spiritual leadership through immense upheaval. He has consistently advocated for nonviolence and compassion, even when it was unpopular, and democratized his own government in exile.",
            dramaticExample: "Voluntarily relinquishing his political authority over the Tibetan government-in-exile in 2011 to empower a democratically elected leader. This act demonstrated his commitment to democratic principles over personal power.",
            capabilities: ["Capability for Compassion Towards Adversaries", "Capability for Spiritual Leadership in Exile", "Capability for Bridging Spiritual and Secular Ethics"],
            relatedChapters: [{ chapter: "2", topic: "Navigating Ethical Terrain" }, { chapter: "6", topic: "Culture, Context, and Life Scripts" }, { chapter: "13", topic: "Political Responsibility" }]
        },
        {
            name: "Malala Yousafzai",
            lifespan: "b. 1997",
            title: "The Fearless Advocate",
            summary: "A Pakistani activist for female education and the youngest Nobel Prize laureate, who survived an assassination attempt by the Taliban.",
            bioLink: "https://www.britannica.com/biography/Malala-Yousafzai",
            videoUrl: null,
            identityKernel: "A firm belief in the right to education for all girls, defined by bravery, optimism, and compassion. Her motto is 'One child, one teacher, one book, one pen can change the world.'",
            prf: "Grew up in Pakistan's Swat Valley under the Taliban, who banned girls from school. Her father, an educator, encouraged her to speak out against this injustice from a young age, creating a context of both oppression and support.",
            futurePull_RMB: "Driven by a vision of a future where all girls can go to school and achieve their potential. This vision fueled her activism even after she was targeted for assassination, pulling her toward a global advocacy role.",
            atcf: "A heroic narrative of resilience. The attempt on her life did not silence her but amplified her voice, transforming her personal trauma into a global movement for education. She consistently advocates for peace and education, not revenge.",
            dramaticExample: "Her speech at the United Nations on her 16th birthday, just nine months after being shot. She declared, 'They thought that the bullets would silence us, but they failed... Weakness, fear and hopelessness died. Strength, power and courage was born.'",
            capabilities: ["Capability for Youth Advocacy on a Global Stage", "Capability for Transforming Trauma into Action", "Capability for Unwavering Optimism"],
            relatedChapters: [{ chapter: "1", topic: "Ethics Begins Where You Are" }, { chapter: "11", topic: "Educational Expeditions" }, { chapter: "6", topic: "Identity, Trauma, and Disruption" }]
        }
    ],
    thinkers: [
        {
            name: "Confucius",
            lifespan: "551-479 BCE",
            title: "The Relational Sage",
            summary: "His PRF emerged from social upheaval, emphasizing relational wisdom and cultural cultivation as the foundation for social harmony.",
            assemblyHistory: "Born into minor nobility during a period of institutional decline, his framework was shaped by a deep reverence for traditional Zhou dynasty rituals and a practical need to address social disorder. His roles as an administrator, teacher, and wandering advisor integrated theoretical wisdom with the practical challenges of governance and moral education.",
            broa: "His BROA+ is centered on relational moral cultivation. Beliefs: Human beings develop through reciprocal care and fulfilling their social roles. Rules: Act with ritual propriety (Li) and benevolent governance (Ren). Ontology: Personhood is constituted through a network of social relationships, not an individual essence. Authenticity: Achieved through the sincere and excellent fulfillment of one's social duties.",
            atcf: "Confucius maintained remarkable coherence by adapting ancient cultural wisdom to contemporary social challenges. He integrated his roles as a scholar, teacher, and political advisor, always aiming to create a framework for social harmony that future generations could inherit and build upon.",
            fop: "His Future-Oriented Projections were focused on creating a durable educational and cultural legacy. He developed systematic approaches to moral education and reinterpreted classical traditions to ensure they would remain relevant for restoring social order and guiding future cultural development.",
            capabilities: ["Capability for Cultural Transmission and Reinterpretation", "Capability for Relational Moral Cultivation", "Capability for Integrating Theory and Governance"],
            videoUrl: null,
        },
        {
            name: "Aristotle",
            lifespan: "384-322 BCE",
            title: "The Systematic Thinker",
            summary: "Synthesized empirical observation with systematic logic to create a comprehensive framework for understanding ethics, politics, and the natural world.",
            assemblyHistory: "His father was a court physician, instilling an early respect for empirical observation. This was combined with twenty years of training in abstract reasoning at Plato's Academy. This unique blend created a tension that fueled his life's work: grounding philosophical ideals in the observable, practical world.",
            broa: "BROA+ is grounded in an empirical and teleological worldview. Beliefs: Knowledge begins with sensory experience, and everything in nature has a purpose (telos). Rules: Virtue is a 'golden mean' between extremes, and valid conclusions come from integrating inductive observation with deductive logic. Ontology: Reality consists of individual substances with essential properties. Authenticity: Achieved through a life that harmonizes intellectual development, ethical character, and political engagement to achieve 'eudaimonia' (flourishing).",
            atcf: "Aristotle consistently integrated his multiple roles as a philosopher, scientist, tutor to Alexander the Great, and founder of his own school, the Lyceum. He adapted Plato's methods but maintained his core commitment to empirical investigation, demonstrating a coherent evolution of thought.",
            fop: "He aimed to create a permanent legacy of systematic knowledge. He organized human understanding into distinct disciplines (logic, physics, ethics) and created a research institution (the Lyceum) designed to continue this work for future generations.",
            capabilities: ["Capability for Systematic Categorization", "Capability for Integrating Empirical and Rational Methods", "Capability for Institutionalizing Knowledge"],
            videoUrl: null,
        },
        {
            name: "Marcus Aurelius",
            lifespan: "121-180 CE",
            title: "The Philosopher Emperor",
            summary: "A Roman Emperor who used Stoic philosophy to navigate the immense pressures of power, war, and personal loss, documenting his struggle for inner coherence in his private Meditations.",
            assemblyHistory: "Born into Roman aristocracy and groomed for power from a young age, he was also deeply immersed in Stoic philosophy. His entire life was a balancing act between the absolute external power of an emperor and the Stoic belief that true good comes only from inner virtue and rational self-control.",
            broa: "His BROA+ is a practical application of Stoicism. Beliefs: The universe is rationally ordered (Logos), and virtue is the only true good. Rules: Begin each day preparing for difficult people; focus only on the present moment; approach others with sympathetic understanding. Ontology: The self is a rational agent participating in a larger cosmic order; death is a natural transformation. Authenticity: Aligning one's inner philosophical commitments with the duties of one's external role, no matter how difficult.",
            atcf: "His Meditations serve as a real-time record of his effort to maintain temporal coherence. Despite plagues, constant warfare on the frontier, and personal betrayals, he consistently returned to his Stoic principles, using his writing to process events and reinforce his identity as a philosopher-emperor.",
            fop: "Aurelius was acutely aware of his legacy. His projections were focused on governing justly, establishing stable precedents for the empire, and providing a personal example of how philosophy can be a practical guide for living a virtuous life even under extreme pressure.",
            capabilities: ["Capability for Self-Examination Under Pressure", "Capability for Integrating Philosophical and Political Roles", "Capability for Maintaining Rational Composure in Crisis"],
            videoUrl: null,
        },
        {
            name: "Augustine of Hippo",
            lifespan: "354-430 CE",
            title: "The Radical Transformer",
            summary: "A theologian and philosopher whose radical personal conversion and intellectual synthesis of classical and Christian thought shaped Western Christianity.",
            assemblyHistory: "Born in Roman North Africa to a pagan father and a devout Christian mother (Monica), his youth was marked by ambition, classical education, and a decade-long adherence to Manichaeism. A profound personal and intellectual crisis led to his famous conversion to Christianity, mediated by Neoplatonic philosophy and the preaching of Ambrose of Milan.",
            broa: "His post-conversion BROA+ is built on the integration of faith and reason. Beliefs: God creates from nothing; evil is the privation of good; salvation comes through divine grace. Rules: Scripture holds ultimate authority, interpreted through philosophical wisdom; authentic Christian life is communal and pastoral. Ontology: A hierarchical creation where all is good, but human will is disordered. Authenticity: 'Faith seeking understanding,' where personal spiritual development must serve the broader community.",
            atcf: "His Confessions is a masterwork of temporal coherence analysis. He successfully integrated his past self (the ambitious rhetorician) with his present self (the Bishop of Hippo) into a coherent narrative of divine grace, preserving his intellectual skills while fundamentally reorienting their purpose.",
            fop: "He projected a future defined by the 'City of God' versus the 'City of Man.' His theological work was designed to provide a durable intellectual and spiritual framework for the Church to navigate the collapse of the Roman Empire and shape future Christian civilization.",
            capabilities: ["Capability for Radical Self-Transformation", "Capability for Theological Synthesis", "Capability for Psychological Self-Analysis"],
            videoUrl: null,
        },
        {
            name: "Ibn Rushd (Averroes)",
            lifespan: "1126-1198 CE",
            title: "The Rational Commentator",
            summary: "An Andalusian philosopher and physician who sought to integrate Aristotelian philosophy with Islamic thought, influencing both Islamic and Western scholasticism.",
            assemblyHistory: "Born in Córdoba into a distinguished family of Islamic judges (qādīs), he was deeply grounded in both Islamic law and the rich Greco-Arabic philosophical tradition of Al-Andalus. His environment was a unique crossroads of Islamic, Jewish, and Christian thought, which he synthesized in his work.",
            broa: "His BROA+ is founded on the harmony of reason and revelation. Beliefs: Philosophy and religion are two paths to the same truth. The natural world operates on rational principles that reveal divine wisdom. Rules: Interpret religious texts at multiple levels (literal for the masses, allegorical for theologians, demonstrative for philosophers). Ontology: An Aristotelian metaphysics of substances and causes, integrated with an emanational cosmology. Authenticity: A life that combines philosophical sophistication with genuine religious commitment and service to the community as a judge and physician.",
            atcf: "He maintained coherence across his multiple roles as philosopher, judge, and physician. Even when he faced persecution and exile for his rationalist views, he maintained his core commitment to the synthesis of philosophy and faith, adapting his communication but not his principles.",
            fop: "He aimed to create a permanent integration of Aristotelian philosophy within Islamic civilization. His comprehensive commentaries on Aristotle were a future-oriented project intended to provide a rational foundation for Islamic thought for generations to come.",
            capabilities: ["Capability for Cross-Cultural Intellectual Synthesis", "Capability for Hierarchical Interpretation", "Capability for Integrating Professional and Philosophical Life"],
            videoUrl: null,
        },
        {
            name: "Thomas Aquinas",
            lifespan: "1225-1274 CE",
            title: "The Theologian Synthesizer",
            summary: "A Dominican friar who created a comprehensive synthesis of Christian theology and Aristotelian philosophy, shaping Western thought for centuries.",
            assemblyHistory: "Born into Italian nobility, he defied his family's wishes by joining the intellectually focused Dominican order. His education under Albert the Great exposed him to the newly rediscovered works of Aristotle, creating the central project of his life: reconciling the systematic rationalism of the Greeks with the revealed truths of Christian faith.",
            broa: "His BROA+ is built on the harmony of faith and reason. Beliefs: Reason and faith both originate from God and cannot truly conflict. Natural reason can understand the created world, while revelation provides truths beyond reason's grasp. Rules: Employ systematic, logical inquiry ('disputed questions') to analyze theological problems, always respecting scriptural authority. Ontology: Reality is a hierarchical order flowing from God, with a distinction between a thing's 'essence' and its 'existence.' Authenticity: An integrated life of rigorous intellectual work and deep contemplative faith, where both serve the Church.",
            atcf: "Aquinas demonstrated remarkable coherence in integrating vast and seemingly contradictory intellectual traditions. His career shows a stable progression from student to master to the author of the monumental Summa Theologica, always maintaining his identity as a faithful scholar serving the Church.",
            fop: "His work was explicitly oriented toward the future of the Church. He created a systematic theological framework and educational method (the Summa) designed to be a permanent resource for training future generations of clergy and theologians, ensuring the Church could engage with the best of secular philosophy.",
            capabilities: ["Capability for Grand Synthesis of Diverse Systems", "Capability for Systematic Theological Argumentation", "Capability for Reconciling Faith and Reason"],
            videoUrl: null,
        },
        {
            name: "Galileo Galilei",
            lifespan: "1564-1642 CE",
            title: "The Experimental Observer",
            summary: "An Italian astronomer, physicist, and engineer whose pioneering use of the telescope and experimental method became a cornerstone of the scientific revolution.",
            assemblyHistory: "His father was a musician and theorist who challenged authority through empirical investigation of sound, providing an early model for Galileo. Living in Renaissance Florence and Padua, he was immersed in a world of artistic innovation and technical craftsmanship, leading him to value direct observation and mathematical precision over traditional scholastic authority.",
            broa: "His BROA+ is grounded in a mathematical and empirical view of nature. Beliefs: The universe is a 'book written in the language of mathematics.' Direct, instrument-aided observation is superior to ancient texts. Rules: Test all theoretical claims with controlled experiments; use technology to extend the senses. Ontology: The cosmos is a unified system governed by universal physical laws, not a hierarchy of separate celestial and terrestrial realms. Authenticity: An unwavering commitment to empirical evidence, even when it conflicts with powerful religious or philosophical authorities.",
            atcf: "Galileo maintained his core identity as a 'mathematical natural philosopher' throughout his life. From his early experiments on motion to his telescopic discoveries and his final, defiant work written under house arrest, he consistently championed the authority of empirical evidence.",
            fop: "He was consciously building a new foundation for science. His Future-Oriented Projections involved establishing an experimental-mathematical method that future investigators could use to progressively unravel the laws of nature, thereby creating a legacy of continuous scientific advancement.",
            capabilities: ["Capability for Empirical Verification", "Capability for Technological Innovation in Science", "Capability for Challenging Dogma with Evidence"],
            videoUrl: null,
        },
        {
            name: "René Descartes",
            lifespan: "1596-1650 CE",
            title: "The Foundational Doubter",
            summary: "A French philosopher, mathematician, and scientist, dubbed the 'father of modern philosophy' for his method of systematic doubt.",
            assemblyHistory: "Educated in the rigorous Jesuit tradition, he became deeply dissatisfied with the lack of certainty in existing philosophy. His experiences in military service and a series of powerful dreams led him to seek a new, indubitable foundation for all knowledge, modeled on the certainty of mathematics.",
            broa: "His BROA+ is built on methodical doubt and rational certainty. Beliefs: Knowledge must be built on foundations that are impossible to doubt ('I think, therefore I am'). The mind (res cogitans) is fundamentally distinct from the body/matter (res extensa). Rules: Accept as true only that which is perceived 'clearly and distinctly.' Break down complex problems into their simplest parts. Ontology: A dualistic universe of mind and matter, with God as the guarantor that our clear ideas correspond to reality. Authenticity: A life of intellectual independence, where truth is discovered through individual reason, not accepted from authority.",
            atcf: "Descartes shows a powerful coherence in his intellectual project. From his early decision to 'raze everything to the ground and begin again from the original foundations,' he systematically executed his philosophical reconstruction over several decades, maintaining his core methodological commitments throughout.",
            fop: "He projected a future where his rational method would unify all human knowledge—from metaphysics to medicine—creating a systematic 'tree of knowledge' that would enable humanity to become 'masters and possessors of nature' for the betterment of all.",
            capabilities: ["Capability for Systematic Doubt", "Capability for Rational Reconstruction of Knowledge", "Capability for Integrating Philosophy and Mathematics"],
            videoUrl: null,
        },
        {
            name: "John Locke",
            lifespan: "1632-1704 CE",
            title: "The Liberal Empiricist",
            summary: "An English philosopher and physician, widely regarded as one of the most influential of Enlightenment thinkers and commonly known as the 'Father of Liberalism.'",
            assemblyHistory: "Shaped by the turmoil of the English Civil War, his Puritan heritage, and his involvement with the emerging scientific revolution (especially through Robert Boyle). His direct experience with political instability and his medical training led him to reject inherited authority in favor of knowledge grounded in experience and observation.",
            broa: "His BROA+ is founded on empiricism and natural rights. Beliefs: All knowledge comes from experience (the mind is a 'tabula rasa'). Individuals possess natural rights to life, liberty, and property. Legitimate government is based on the consent of the governed. Rules: Base beliefs on evidence, not authority. Government must be limited by a constitution and separation of powers. Ontology: The individual is the fundamental moral and political unit. Authenticity: A life of rational independence, where beliefs are formed through individual reason and political participation is a responsibility.",
            atcf: "Locke showed consistency from his early medical and scientific work to his later political philosophy. He consistently applied an empirical, evidence-based method to questions of both knowledge and politics, maintaining his core commitments through political upheaval and exile.",
            fop: "He was designing a blueprint for a stable, free, and prosperous future society. His projections included constitutional democracy, religious tolerance, and a system of education that would prepare citizens for self-governance, all aimed at long-term human progress.",
            capabilities: ["Capability for Grounding Political Theory in Empiricism", "Capability for Designing Constitutional Limits on Power", "Capability for Theorizing Individual Rights"],
            videoUrl: null,
        },
        {
            name: "Immanuel Kant",
            lifespan: "1724-1804 CE",
            title: "The Critical Philosopher",
            summary: "A German philosopher whose comprehensive and systematic work in epistemology, metaphysics, ethics, and aesthetics made him one of the most influential figures in modern Western philosophy.",
            assemblyHistory: "His PRF was formed in the relatively isolated city of Königsberg, shaped by a devout Pietist upbringing (emphasizing inner moral duty) and the rationalist philosophy of Leibniz and Wolff. The skeptical challenge of David Hume awakened him from his 'dogmatic slumber,' forcing him to undertake a 'Copernican Revolution' in philosophy.",
            broa: "His BROA+ is the foundation of his Critical Philosophy. Beliefs: We can only know the world as it appears to us (phenomena), structured by the mind's own categories. Moral law is derived from pure reason itself. Rules: The Categorical Imperative—act only according to principles you could will to be universal laws, and always treat humanity as an end, never merely as a means. Ontology: A dual view of reality—the phenomenal world of experience and the noumenal world of things-in-themselves, which allows for both scientific determinism and moral freedom. Authenticity: A life of rational autonomy, where one thinks for oneself and acts according to self-given moral laws.",
            atcf: "Kant's life was one of extraordinary intellectual consistency. After his 'critical turn' around 1770, he spent the rest of his life systematically and coherently building his philosophical system, from the Critique of Pure Reason to his final essays on politics and history.",
            fop: "He projected a future of 'perpetual peace' and a global 'republican' order guided by reason. His entire philosophical system was a future-oriented project aimed at providing a permanent, rational foundation for science, morality, and political progress for all of humanity.",
            capabilities: ["Capability for Systematic Critique of Reason", "Capability for Formulating Universal Moral Principles", "Capability for Synthesizing Rationalism and Empiricism"],
            videoUrl: null,
        },
        {
            name: "Jeremy Bentham",
            lifespan: "1748-1832 CE",
            title: "The Utilitarian Reformer",
            summary: "An English philosopher, jurist, and social reformer regarded as the founder of modern utilitarianism.",
            assemblyHistory: "A child prodigy trained in law, he became deeply disillusioned with the arbitrary and inefficient English legal system. Influenced by Enlightenment thinkers, he sought to replace tradition and 'natural law' with a scientific, rational foundation for law and morality based on empirical human psychology.",
            broa: "His BROA+ is grounded in psychological hedonism and utility maximization. Beliefs: Human beings are governed by two sovereign masters, pain and pleasure. The only rational moral goal is to maximize the total quantity of happiness ('the greatest good for the greatest number'). Rules: The 'Felicific Calculus'—evaluate all actions and policies by systematically calculating their consequences for human happiness. Ontology: A materialist psychology where mind is an emergent property; social institutions are human constructs to be engineered for utility. Authenticity: A life of impartial benevolence guided by systematic rational calculation, free from tradition and sentiment.",
            atcf: "Bentham exhibited remarkable consistency in applying his utilitarian principle to every aspect of society. From his critique of legal fictions to his design for the 'Panopticon' prison and his advocacy for democratic reform, he relentlessly followed his core methodology.",
            fop: "He projected a future where all social institutions—law, government, education, economics—would be rationally designed to maximize public welfare. He founded a movement of 'Philosophical Radicals' to carry this systematic reform project into the future.",
            capabilities: ["Capability for Systematic Social Calculation", "Capability for Institutional Design and Innovation", "Capability for Critiquing Traditional Authority"],
            videoUrl: null,
        },
        {
            name: "John Stuart Mill",
            lifespan: "1806-1873 CE",
            title: "The Liberal Synthesizer",
            summary: "A British philosopher, political economist, and civil servant who was an influential proponent of utilitarianism and liberalism.",
            assemblyHistory: "He was the subject of a rigorous, experimental education by his father, James Mill, designed to create a perfect utilitarian thinker. This intense intellectual training was followed by a 'mental crisis' in his twenties, which led him to integrate Romanticism, emotional development, and the value of individuality into his inherited Benthamite framework. His lifelong intellectual partnership with Harriet Taylor was also fundamental to his development, especially his radical views on gender equality.",
            broa: "His BROA+ represents a qualified utilitarianism. Beliefs: Human happiness includes 'higher' (intellectual, moral) and 'lower' (sensual) pleasures. Individual liberty is essential for personal development and social progress. Rules: The 'Harm Principle'—liberty should only be restricted to prevent harm to others. Encourage 'experiments in living.' Ontology: Individuals and society are interdependent; history is progressive. Authenticity: A life that balances rational analysis with emotional development and serves social improvement.",
            atcf: "Mill's life is a story of coherent synthesis. He successfully integrated the severe rationalism of his upbringing with the Romantic value of individuality, and his philosophical work with his practical engagement as a Member of Parliament, consistently adapting his views based on new insights without losing his core commitment to human progress.",
            fop: "He projected a future of a mature liberal democracy, where educated citizens participate in governance, individual liberty is maximized, and gender equality is achieved. His works like 'On Liberty' and 'The Subjection of Women' were written as guides for this ongoing project of social reform.",
            capabilities: ["Capability for Synthesizing Conflicting Philosophies", "Capability for Championing Individual Liberty", "Capability for Radical Empathy and Gender Equality Advocacy"],
            videoUrl: null,
        },
        {
            name: "Peter Singer",
            lifespan: "1946-Present",
            title: "The Applied Ethicist & Altruist",
            summary: "A contemporary philosopher whose application of utilitarianism to animal rights and global poverty sparked the effective altruism movement.",
            assemblyHistory: "Born in Melbourne to Jewish Austrian parents who escaped the Holocaust, his framework was shaped by a secular upbringing that valued rational inquiry and a deep awareness of the consequences of ethical indifference. His philosophical development at Oxford in the 1960s, a time of social upheaval, solidified his commitment to applying rigorous utilitarian analysis to real-world problems.",
            broa: "His BROA+ is grounded in utilitarian consequentialism. Beliefs: The right action is the one that maximizes welfare for all affected beings. The capacity for suffering (sentience) is the basis for moral consideration. Rules: Impartially maximize welfare; act on evidence of what is most effective; apply principles consistently. Ontology: A naturalistic worldview with a global moral community that includes all sentient beings. Authenticity: A life where one's actions (like charitable giving and lifestyle choices) are consistent with one's stated moral beliefs about reducing suffering.",
            atcf: "Singer has shown remarkable consistency in applying his utilitarian principles across an expanding range of issues, from his groundbreaking work on animal liberation to his arguments on global poverty and effective altruism. He consistently follows the logical conclusions of his framework, even when they are controversial.",
            fop: "He projects a future where the 'moral circle' continues to expand, and where reason and evidence guide our ethical choices. He actively works to build the 'Effective Altruism' movement as an institutional legacy to ensure that future generations can reduce suffering and improve the world more effectively.",
            capabilities: ["Capability for Applied Ethical Innovation", "Capability for Expanding the Moral Circle", "Capability for Public Intellectual Communication", "Capability for Cross-Disciplinary Synthesis"],
            videoUrl: null,
        },
        {
            name: "Derek Parfit",
            lifespan: "1942-2017",
            title: "The Identity Revisionist",
            summary: "A British philosopher who made groundbreaking contributions to personal identity, ethics, and rationality, known for his rigorous use of thought experiments.",
            assemblyHistory: "Shaped by an elite British education (Eton, Oxford) and a deep fascination with puzzles of identity and time. His work was a reaction against what he saw as imprecise thinking in moral philosophy, aiming to bring mathematical rigor to questions of what matters.",
            broa: "His BROA+ is built on a reductionist and impartial view of ethics. Beliefs: Personal identity is not what truly matters; psychological continuity is. There may not be a single 'best' moral theory, but different theories might converge on the same conclusions. Rules: Use thought experiments to test intuitions; strive for logical precision; give equal weight to the well-being of all people, including those in the distant future. Ontology: A naturalistic worldview where complex phenomena like 'the self' reduce to simpler physical and psychological events. Authenticity: An unwavering commitment to intellectual honesty, following arguments wherever they lead, regardless of how counterintuitive the conclusions.",
            atcf: "Parfit's life was one of extreme intellectual coherence. He spent decades meticulously working on his major books, *Reasons and Persons* and *On What Matters*, ensuring every argument was as precise as possible. His identity as a systematic, analytical philosopher never wavered.",
            fop: "He was deeply concerned with the long-term future of humanity. His work on population ethics and future generations was a direct attempt to build a rational framework for making choices that would have the best consequences for all people who will ever live.",
            capabilities: ["Capability for Systematic Philosophical Architecture", "Capability for Thought Experiment Innovation", "Capability for Future-Oriented Moral Focus"],
            videoUrl: null,
        },
        {
            name: "Martha Nussbaum",
            lifespan: "1947-Present",
            title: "The Capabilities Proponent",
            summary: "An American philosopher who champions the 'Capabilities Approach,' arguing that social justice means ensuring every individual has the real opportunity to develop their essential human capabilities.",
            assemblyHistory: "Her framework was formed through a combination of classical philosophy (especially Aristotle), literary studies, and a growing engagement with feminist theory and international development. Her early training as an actor also gave her a deep appreciation for the role of emotions and narrative in moral life.",
            broa: "Her BROA+ is grounded in an Aristotelian and universalist humanism. Beliefs: All humans share a set of central capabilities essential for a flourishing life. Emotions are cognitive and provide vital information for moral reasoning. Rules: Evaluate societies and policies based on whether they provide citizens with the necessary conditions to develop their capabilities. Ontology: A pluralistic view of value; human flourishing is multi-dimensional and cannot be reduced to a single metric like money. Authenticity: An integrated life where intellectual rigor, emotional intelligence, and a commitment to social justice are intertwined.",
            atcf: "Nussbaum has demonstrated remarkable consistency in applying and developing her Capabilities Approach across diverse fields, from ancient Greek ethics to modern constitutional law and international development policy. She coherently integrates philosophical analysis, literary interpretation, and practical policy advocacy.",
            fop: "She projects a future where global justice and national policies are evaluated not by GDP, but by how well they secure a threshold of central capabilities for every single person, creating a more humane and just world.",
            capabilities: ["Capability for Interdisciplinary Synthesis", "Capability for Cross-Cultural Translation", "Capability for Integrating Emotion and Reason"],
            videoUrl: null,
        },
        {
            name: "Kwame Anthony Appiah",
            lifespan: "1954-Present",
            title: "The Rooted Cosmopolitan",
            summary: "A British-Ghanaian philosopher whose work on identity, culture, and cosmopolitanism argues for a world where universal moral concern coexists with respect for particular cultural identities.",
            assemblyHistory: "His unique bicultural upbringing—son of an Asante royal and politician in Ghana and a British aristocrat and author in England—provided him with a direct, lived experience of navigating multiple identities. His education at Cambridge grounded him in the analytical tradition of philosophy, which he then applied to questions of race, culture, and postcolonial identity.",
            broa: "His BROA+ is defined by 'rooted cosmopolitanism.' Beliefs: We have moral obligations to all human beings, but our particular identities and cultural affiliations also have real value. Identity is not an essence but something we choose and construct from available cultural 'scripts.' Rules: Engage in respectful dialogue across cultures; respect individual choices about identity. Ontology: Race is a social construct, not a biological reality, but it has real-world effects. Authenticity: A life that coherently integrates one's multiple cultural affiliations and moral commitments, embracing complexity over purity.",
            atcf: "Appiah's life and work show a consistent effort to bridge divides—between cultures, between academic philosophy and public discourse, and between universal ethics and particular identities. He has maintained a coherent philosophical project while adapting to different institutional and cultural contexts in Ghana, the UK, and the US.",
            fop: "He projects a future of global conversation, where people can learn from different cultural traditions without abandoning their own. His work aims to provide the philosophical tools for a globalized world to manage cultural difference peacefully and productively.",
            capabilities: ["Capability for Cross-Cultural Translation", "Capability for Public Intellectual Integration", "Capability for Deconstructing Essentialist Identities"],
            videoUrl: null,
        }
    ],
    concepts: [
        { 
            name: "Personal Reality Framework (PRF)",
            description: "An agent's unique architecture for organizing experience, comprising their Beliefs, Rules, Ontological commitments, and Authenticity criteria (BROA+). It's a dynamic system, shaped by a person's life story (Assembly History), that filters perception and guides action."
        },
        {
            name: "Capability-Based Coordination & Functional Equivalence",
            description: "The core principle that ethical coordination doesn't require people to share identical beliefs or values. Instead, they can coordinate effectively by developing 'functionally equivalent' capabilities that achieve the same shared goal. Different paths, same ethical function."
        },
        {
            name: "Adaptive Temporal Coherence Function (ATCF)",
            description: "A measure of an agent's ability to maintain identity and integrity over time. It assesses how well one integrates their past experiences, present actions, and future aspirations into a coherent narrative. High ATCF is a mark of ethical maturity and resilience."
        },
        {
            name: "Bootstrap Resolution of Normative Authority",
            description: "The meta-ethical idea that the 'ought' of ethics emerges from the practical necessities of being an agent. Any person who can ask 'Why should I be ethical?' already demonstrates a commitment to the temporal coherence and reasoning that ground ethical coordination. Authority comes from within agency itself."
        },
        {
            name: "Network-Goal Coordination",
            description: "A form of collaboration where diverse stakeholders advance the *same shared network objective* (e.g., 'establish truth and prevent harm') through their different but equivalent skills. This is more resilient than coordination based on temporarily aligned individual interests."
        },
        {
            name: "Cross-Scale Markup Organization",
            description: "The principle that universal information architecture patterns enable coordination across different systems (e.g., biological cells, human consciousness, computer networks). It suggests a deep structural link between logical reasoning and ethical coordination."
        }
    ]
};

